apiVersion: v1
kind: Service
metadata:
  name: test-app-loadbalancer
  labels:
    app: test-app-loadbalancer
spec:
  selector:
    app: test-app-loadBalancer
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 3000